version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run:
          name: Copy .env.testing file
          command: cp .env.testing .env
      - run: php --version
      - run: vendor/bin/phpunit
