version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: php --version
      - run:
          name: Start Laravel Sail
          command: |
            cd coachtech/coachtech-flea-market
            ./vendor/bin/sail up -d
      - run:
          name: Run PHPUnit with Laravel Sail
          command: |
            cd coachtech/coachtech-flea-market
            ./vendor/bin/sail artisan test
      - run:
          name: Stop Laravel Sail
          command: |
            cd coachtech/coachtech-flea-market
            ./vendor/bin/sail down
