version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: php --version
      # Laravel Sailの起動とテスト実行
      - run:
          name: Start Laravel Sail
          command: ./vendor/bin/sail up -d
      - run:
          name: Run PHPUnit with Laravel Sail
          command: ./vendor/bin/sail artisan test
      # Laravel Sailの停止
      - run:
          name: Stop Laravel Sail
          command: ./vendor/bin/sail down
