version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: php --version
      - run:
          name: Install Laravel dependencies
          command: composer install
      - run:
          name: Install Laravel Sail
          command: composer require laravel/sail --dev
      - run:
          name: Run PHPUnit tests with Laravel Sail
          command: vendor/bin/sail artisan test
