version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.2.7

    steps:
      - checkout

      # Create Environment file and generate app key



      # Run tests with phpunit
      - run:
          name: "Run Tests"
          command: ./vendor/bin/sail artisan test --env=testing
