version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          APP_DEBUG: true
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: sail
          DB_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            composer install -n --ignore-platform-reqs
            cp .env.example .env
            php artisan key:generate
      - run:
          name: Run Tests
          command: |
            php artisan test
