version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: php --version
      - run:
          name: Install Laravel dependencies
          command: composer install
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit
