version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Docker Compose
          command: docker-compose up -d
      - run:
          name: Install Dependencies
          command: docker-compose exec laravel.test composer install
      - run:
          name: Run Tests
          command: docker-compose exec laravel.test ./vendor/bin/phpunit
workflows:
  version: 2
  build:
    jobs:
      - build
