version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/php:8.2.7

    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: sudo apt-get update && sudo apt-get install -y npm
      - run: npm ci
      - run: vendor/bin/phpunit
