version: 2.1

jobs:
  build:
    docker:
      - image: sail-10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Laravel Sailのセットアップ
      - run:
          name: Install Sail dependencies
          command: |
            alias sail='bash vendor/bin/sail'
            sail up -d
            sail composer install

      # データベースのセットアップとテストの実行
      - run:
          name: Setup Database and Run Tests
          command: |
            sail artisan migrate --seed
            sail test
