version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Copy Environment File
          command: cp .env.example .env

      - run:
          name: Install Dependencies
          command: composer install
          
      - run:
          name: Generate Application Key
          command: php artisan key:generate
      - run:

          name: Run Tests
          command: vendor/bin/phpunit
