version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run:
          name: Install Laravel Sail
          command: |
            composer require laravel/sail --dev
            php artisan sail:install
      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/sail artisan test
