version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:20.10.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker compose
          command: |
            apk add py-pip
            pip install docker-compose
      - run:
          name: Start Docker Compose
          command: docker-compose up -d
      - run:
          name: Install Dependencies
          command: docker-compose exec laravel.test composer install
      - run:
          name: Run Tests
          command: docker-compose exec laravel.test ./vendor/bin/phpunit
workflows:
  version: 2
  build:
    jobs:
      - build
