version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: 
          name: Setup Laravel Sail
          command: |
            # Install dependencies
            sudo apt-get update
            sudo apt-get install -y libsqlite3-dev libsqlite3-0 mariadb-client
            curl -s https://laravel.build/example-app | bash
      - run:
          name: Start Laravel Sail
          command: |
            cd example-app
            ./vendor/bin/sail up -d
            sleep 30 # Wait for containers to start
      - run:
          name: Install Composer dependencies
          command: |
            cd example-app
            php composer.phar install --ignore-platform-reqs
      - run:
          name: Run Laravel tests
          command: |
            cd example-app
            ./vendor/bin/sail artisan test
      - run:
          name: Tear down Laravel Sail
          command: |
            cd example-app
            ./vendor/bin/sail down
