version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/php:8.2.7

    steps:
      - checkout
      - run: sudo composer self-update --2
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
