version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.3
    steps:
      - checkout
      - run: sudo composer self-update --2
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit

