version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:20.10.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
