version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: php --version
      - run:
          name: "Create database and run migration"
          command: |
            touch storage/testing.sqlite
            php artisan migrate --env=testing
      - run:
          name: "テスト"
          command: |
            ./vendor/bin/phpunit
