version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/php:8.2.7

    steps:
      - checkout
      - run: composer install -n --prefer-dist
      # npmコマンドを削除し、ビルドされたJavaScriptファイルを使ってテストを実行する
      - run: npm run build
      - run: vendor/bin/phpunit
