version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.3
    steps:
      - checkout
      - run: php --version
      - run:
          name: Run PHPUnit with Laravel Sail
          command: ./vendor/bin/sail artisan test

